Mui integration
proga-react-practice/delta-andrii-vovk pull request #2
Opened 2024-04-29 11:50 UTC by Thundem

![зображення](https://github.com/proga-react-practice/delta-andrii-vovk/assets/123400564/901c2ab3-ae92-40c6-8036-a6475f6f5c4a)
![зображення](https://github.com/proga-react-practice/delta-andrii-vovk/assets/123400564/78d7a1b9-eaa7-4d0a-be7e-d38607b361b5)
![зображення](https://github.com/proga-react-practice/delta-andrii-vovk/assets/123400564/249a5afd-bb08-4d10-a4b0-d861ddacdab8)

Link to video:
https://www.awesomescreenshot.com/video/27201031?key=18eed88c9b749e0e271c63a7f8eb0a31

2024-04-29 18:13 UTC, Emil-Khalus requested changes

2024-04-29 18:13 UTC, Emil-Khalus commented on src/App.tsx
> +  }
Try to use the standard breakpoint values for changing styles depending on the width of the screen, which are defined in the MUI. This will help standardize styles for a specific screen width and simplify your code. For example, you can describe your styles in this way: `flexDirection: {xs: "column", md: "row"}` or something like that

https://mui.com/material-ui/customization/breakpoints/

2024-04-29 18:13 UTC, Emil-Khalus commented on src/App.tsx
> +            isMobile ?
The same goes for the way you check the screen width for mobile. You can use the `useMediaQuery` hook from the MUI instead of creating a separate state and using the `useEffect`

2024-04-29 18:13 UTC, Emil-Khalus commented on src/components/FormResult.tsx
> +}));
try to put all the colors you set here in the mui theme and use them from the theme itself

2024-04-29 18:15 UTC, Emil-Khalus commented
These comments should be heeded throughout the project. Also, please add screenshots/video of your form, how it looks on desktop and mobile

2024-04-29 18:58 UTC, Thundem commented on src/App.tsx
> +  }
I'll fix it

2024-04-29 19:06 UTC, Thundem commented on src/App.tsx
> +  }
![зображення](https://github.com/proga-react-practice/delta-andrii-vovk/assets/123400564/ce4f25cb-e408-44fa-8635-99b53dedea59)

2024-04-29 19:29 UTC, Thundem commented on src/components/FormResult.tsx
> +}));
![зображення](https://github.com/proga-react-practice/delta-andrii-vovk/assets/123400564/60bd155c-8919-4b90-824c-d4a85f3a2c86)
![зображення](https://github.com/proga-react-practice/delta-andrii-vovk/assets/123400564/e1decf51-e930-434d-bf87-a3e5e16cbb0d)

2024-04-29 19:46 UTC, Thundem commented on src/App.tsx
> +            isMobile ?
So, instead of usingEffect, I can use useMediaQuery to check the width of the screen?

2024-04-29 19:48 UTC, Emil-Khalus commented on src/App.tsx
> +            isMobile ?
Yes, you can replace useEffect logic with useMediaQuery

2024-04-29 19:55 UTC, Thundem commented on src/App.tsx
> +            isMobile ?
Ok, I'll fix it

2024-04-29 21:19 UTC, Thundem commented on src/App.tsx
> +            isMobile ?
![зображення](https://github.com/proga-react-practice/delta-andrii-vovk/assets/123400564/548abc9e-42e8-4c8b-8ecd-decb51ab6888)

2024-04-30 07:47 UTC, Emil-Khalus approved these changes

2024-04-30 07:47 UTC, Emil-Khalus commented on src/components/RentCarForm.tsx
> +        color: '#ffffff',
please replace hardcoded color with color from theme

2024-04-30 07:47 UTC, Emil-Khalus commented on src/components/RentCarForm.tsx
> +                }}
I think if TextField error porp is true then TextField `borderColor` will be change automatically and we don't need this check

2024-04-30 07:47 UTC, Emil-Khalus commented on src/components/RentCarForm.tsx
>              />
You pass almost the same styles to all TextFields. What do you think about creating a separate component for the TextField that has these defaults?

2024-04-30 07:50 UTC, Emil-Khalus commented
showing additional validation error text under the TextField will be a better UX than just highlighting the input in red

![image](https://github.com/proga-react-practice/delta-andrii-vovk/assets/79042240/887bc8f5-3ca9-4a54-a9c1-dcc67d60f123)

2024-04-30 08:14 UTC, Emil-Khalus commented
On your video, the start date is immediately highlighted in red. Then you changed it, the validation error disappeared, but after clicking submit, the card was added and the start date turned red again. It seems that your validation is not working correctly

![image](https://github.com/proga-react-practice/delta-andrii-vovk/assets/79042240/9b070a6b-565b-4931-8c44-241694c65df3)

2024-04-30 08:32 UTC, Thundem commented on src/components/RentCarForm.tsx
> +        color: '#ffffff',
![зображення](https://github.com/proga-react-practice/delta-andrii-vovk/assets/123400564/15ec4ec2-a155-4074-9471-3a1ecb4ef007)

2024-04-30 11:58 UTC, Thundem commented on src/components/RentCarForm.tsx
>              />
Did I understand correctly that I need to do this?
![зображення](https://github.com/proga-react-practice/delta-andrii-vovk/assets/123400564/6e5b41cd-f6f7-4b36-87fc-e1574a3d9f4a)

2024-04-30 14:38 UTC, merged