Mui integration
proga-react-practice/delta-andrii-vovk pull request #3
Opened 2024-05-04 18:33 UTC by Thundem

2024-05-07 10:56 UTC, Emil-Khalus commented
In your video, you can see that a validation error is displayed after the summit. What do you think about clearing these inputs after the form submission and validating them only when the user edits them?
![image](https://github.com/proga-react-practice/delta-andrii-vovk/assets/79042240/60a194da-0768-4655-ab49-2450c5077597)

2024-05-07 11:00 UTC, Emil-Khalus requested changes

2024-05-07 11:27 UTC, Thundem commented
I already fixed it

2024-05-07 11:37 UTC, Thundem commented on src/components/styledComponents/StyledComponent.tsx
If I understand correctly, i need to move each styled components in separate files?

2024-05-07 11:39 UTC, Thundem commented
I already fixed bug with startRentTime component, but I forgot refresh my video

2024-05-24 18:44 UTC, mykyta07 approved these changes

2024-05-29 13:19 UTC, merged